# --- // 4ndr0 fonts.toml // ========

[font]
size = 10

builtin_box_drawing = true

# --- // Normal:
[font.normal]
family = "monaco nerd font"
style = "Regular"

# --- // Bold:
[font.bold]
family = "monaco nerd font"
style = "Bold"

# --- // Italic:
[font.bold_italic]
family = "monaco nerd font"
style = "Bold Italic"

# --- // Bold italic:
[font.italic]
family = "monaco nerd font"
style= "Italic"

[font.offset]
x = 0
y = 0

# --- // Glyph offset:
[font.glyph_offset]
x = 0
y = 0
