# Shell variables
# Generated by 'wal'
wallpaper='/home/andro/Wallpapers/wallpaper.jpg'

# Special
background='#070C15'
foreground='#c7cad1'
cursor='#c7cad1'

# Colors
color0='#070C15'
color1='#5C626E'
color2='#666C78'
color3='#717884'
color4='#7C828F'
color5='#838996'
color6='#9298A5'
color7='#c7cad1'
color8='#8b8d92'
color9='#5C626E'
color10='#666C78'
color11='#717884'
color12='#7C828F'
color13='#838996'
color14='#9298A5'
color15='#c7cad1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
