" Generated by vim-plug
" Mon 30 Sep 2024 07:38:14 PM CDT
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['ale'].commit = 'a7ef1817b7aa06d0f80952ad530be87ad3c8f6e2'
silent! let g:plugs['cmp-nvim-lsp'].commit = '39e2eda76828d88b773cc27a3f61d2ad782c922d'
silent! let g:plugs['fzf'].commit = '4161403a1d6286f6ba7898b1f22f30d01d85b8dc'
silent! let g:plugs['fzf.vim'].commit = 'c5ce7908ee86af7d4090d2007086444afb6ec1c9'
silent! let g:plugs['goyo.vim'].commit = 'fa0263d456dd43f5926484d1c4c7022dfcb21ba9'
silent! let g:plugs['lightline.vim'].commit = 'd6a07ea376a4b7372aa59e7ea6a051c9470bb4d0'
silent! let g:plugs['nerdtree'].commit = '9b465acb2745beb988eff3c1e4aa75f349738230'
silent! let g:plugs['nerdtree-git-plugin'].commit = 'e1fe727127a813095854a5b063c15e955a77eafb'
silent! let g:plugs['nightfox.nvim'].commit = '7557f26defd093c4e9bc17f28b08403f706f5a44'
silent! let g:plugs['nvim-cmp'].commit = 'ae644feb7b67bf1ce4260c231d1d4300b19c6f30'
silent! let g:plugs['nvim-lspconfig'].commit = '0678aa439b82965daf03679cd146e84f10e299c3'
silent! let g:plugs['tabular'].commit = '12437cd1b53488e24936ec4b091c9324cafee311'
silent! let g:plugs['undotree'].commit = '78b5241191852ffa9bb5da5ff2ee033160798c3b'
silent! let g:plugs['vim-airline'].commit = '81eca994860645acbb58442285cdd70df5c71d2b'
silent! let g:plugs['vim-auto-save'].commit = '2e3e54ea4c0fc946c21b0a4ee4c1c295ba736ee8'
silent! let g:plugs['vim-commentary'].commit = 'c4b8f52cbb7142ec239494e5a2c4a512f92c4d07'
silent! let g:plugs['vim-css-color'].commit = '950e80352b325ff26d3b0faf95b29e301c200f7d'
silent! let g:plugs['vim-devicons'].commit = '71f239af28b7214eebb60d4ea5bd040291fb7e33'
silent! let g:plugs['vim-markdown'].commit = '8f6cb3a6ca4e3b6bcda0730145a0b700f3481b51'
silent! let g:plugs['vim-mucomplete'].commit = '03bcd4a7dfe0a2f6d432e8ce936d35273a15209d'
silent! let g:plugs['vim-surround'].commit = '3d188ed2113431cf8dac77be61b842acb64433d9'
silent! let g:plugs['vimagit'].commit = 'fc7eda97da4f8182c8abbe6ea7befbd789b8b935'
silent! let g:plugs['vimwiki'].commit = '705ad1e0dded0e3b7ff5fac78547ab67c9d39bdf'

PlugUpdate!

