" Generated by vim-plug
" Mon 22 Apr 2024 11:54:46 AM CDT
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['goyo.vim'].commit = 'fa0263d456dd43f5926484d1c4c7022dfcb21ba9'
silent! let g:plugs['nerdtree'].commit = 'f3a4d8eaa8ac10305e3d53851c976756ea9dc8e8'
silent! let g:plugs['vim-airline'].commit = 'd9f42cb46710e31962a9609939ddfeb0685dd779'
silent! let g:plugs['vim-commentary'].commit = 'c4b8f52cbb7142ec239494e5a2c4a512f92c4d07'
silent! let g:plugs['vim-css-color'].commit = '950e80352b325ff26d3b0faf95b29e301c200f7d'
silent! let g:plugs['vim-surround'].commit = '3d188ed2113431cf8dac77be61b842acb64433d9'
silent! let g:plugs['vimagit'].commit = 'fc7eda97da4f8182c8abbe6ea7befbd789b8b935'
silent! let g:plugs['vimwiki'].commit = '69318e74c88ef7677e2496fd0a836446ceac61e8'

PlugUpdate!
