[terminal]
vt = 1
command = "gtkgreet --provider wayland"
user = "greeter"

[default_session]
command = "dbus-run-session -- bash /usr/bin/run-wayfire"
user = "andro"
#command = "dbus-run-session -- wayfire"
#command = "wayfire --config /home/andro/.config/wayfire.ini"
#command = "wayfire --config /etc/greetd/wconfig > /dev/null 2>&1"
#command = "agreety --cmd wayfire"
#command = "wayfire wlgreet"

#[initial_session]
#user = "andro"
#command = "sway"
