#!/usr/bin/env bash

#File: run-wayfire
#Author: 4ndr0666
#Edited: 5-19-24
# Exports environment variables for wayfire and launches it.
#
# --- // RUN-WAYFIRE // ========


# --- // XDG_VARIABLES:
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=wayfire
export XDG_CURRENT_DESKTOP=wayfire
export XDG_CURRENT_SESSION=wayfire

# --- // EXPLICITY_SET_WAYFIRE_DIRS:
XDG_DATA_DIRS=$XDG_DATA_DIRS

if [ -d "XDG_DATA_HOME" ]; then
    DEFAULT_LOG_DIR=$XDG_DATA_HOME/wayfire
else
    DFAULT_LOG_DIR=$HOME/.local/share/wayfire
fi

# --- // SETUP_LOGGING:
mkdir -p $DEFAULT_LOG_DIR
if [ $? != 0 ]; then
    echo "Could not create log directory $DEFAULT_LOG_DIR"
    echo "Using stdout as log"
    wayfire "$@"
 elif [ ! -z "$WAYLAND_DISPLAY" ] || [ ! -z "$DISPLAY" ]; then
     echo "RUnning nested, using stdout as log"
     wayfire "$@"
 else
     LOG_FILE=$DEFAULT_LOG_DIR/wayfire.log
     if [ -f $LOG_FILE ]; then
         cp $LOG_FILE $LOG_FILE.old
     fi
     echo "Using log file: $LOG_FILE"
     wayfire "@" &> $LOG_FILE
 fi
 
# --- // GTK_VARIABLES:
export TDESKTOP_DISABLE_GTK_INTEGRATION=1
export CLUTTER_BACKEND=wayland,x11
export BEMENU_BACKEND=wayland


export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORMTHEME=qt5ct
export AWT_TOOLKIT="MTookit wmname LG3D"
export _JAVA_AWT_WM_NONREPARENTING=1
export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel ${_JAVA_OPTIONS}"

export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_QPA_PLATFORM=wayland-egl  # Avoid using xcb for Wayland sessions
export QT_WAYLAND_FORCE_DPI=physical # Use monitor's DPI
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1


export ELM_DISPLAY=wl
export ECORE_EVAS_ENGINE=wayland-egl
export ELM_ENGINE=wayland_egl
export ELM_ACCEL=opengl
#export ELM_SCALE=1


export SDL_VIDEODRIVER=wayland
export SAL_USE_VCLPLUGIN=gtk3

export GDK_BACKEND=wayland,x11
export NO_AT_BRIDGE=1
export WINIT_UNIX_BACKEND=wayland

export ELECTRON_OZONE_PLATFORM_HINT=wayland

# --- // SYSTEMD_DBUS:
if ! eval "$(dbus-launch --sh-syntax)"; then
    echo "Failed to launch D-Bus session bus."
    exit 1
fi
export DBUS_SESSION_BUS_ADDRESS
export DBUS_SESSION_BUS_PID
#xhost + </dev/null &>/dev/null &
#xhost +SI:localuser:andro
#xhost +SI:localuser:root

# --- // EXEC_WAYFIRE:
sleep 0.5

if ! command -v wayfire &> /dev/null; then
    echo "Wayfire could not be found, please install it."
    exit 1
fi

wayfire
