// ==UserScript==
// @name         Export Cookies in Netscape Format
// @namespace    http://tampermonkey.net/
// @version      1.0
// @description  Extract current site's cookies and export them as a Netscape formatted file.
// @match        http*://*
// @grant        none
// @run-at       document-end
// ==/UserScript==

(function() {
    'use strict';

    // Create and style the export button
    const btn = document.createElement('button');
    btn.textContent = 'Export Cookies (Netscape)';
    btn.style.position = 'fixed';
    btn.style.top = '10px';
    btn.style.right = '10px';
    btn.style.zIndex = 10000;
    btn.style.padding = '8px';
    btn.style.backgroundColor = '#4CAF50';
    btn.style.color = 'white';
    btn.style.border = 'none';
    btn.style.borderRadius = '4px';
    btn.style.cursor = 'pointer';
    document.body.appendChild(btn);

    // Function to export cookies in Netscape format
    function exportCookiesNetscape() {
        const hostname = document.location.hostname;
        const secureFlag = (location.protocol === 'https:') ? 'TRUE' : 'FALSE';
        // Retrieve cookies from document.cookie (only non-HttpOnly cookies available)
        const cookies = document.cookie.split(';').map(c => c.trim()).filter(c => c !== '');
        
        // Build Netscape cookie file header
        let fileContent = "# Netscape HTTP Cookie File\n";
        fileContent += "# This file was generated by a userscript.\n";
        fileContent += "# Do not edit.\n\n";
        
        // Format each cookie as: domain, flag, path, secure, expiry, name, value
        cookies.forEach(cookieStr => {
            const [name, ...rest] = cookieStr.split('=');
            const value = rest.join('=');
            // Use current hostname with a leading dot for domain field
            const domain = hostname.startsWith('.') ? hostname : '.' + hostname;
            // Set expiry to 0 (session cookie) as expiry data is not available via document.cookie
            fileContent += `${domain}\tTRUE\t/\t${secureFlag}\t0\t${name}\t${value}\n`;
        });
        
        // Create a Blob and trigger download
        const blob = new Blob([fileContent], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${hostname}_cookies.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    }

    // Add click event to the button
    btn.addEventListener('click', exportCookiesNetscape);
})();
