--loop-file=inf
--speed=0.50
#osc=no
#--loop-playlist=yes
#setpts=PTS*2
#For best practices and proper workflow, place the desired profile first in the config
#followed by the neccessary gpu options. Enter the desired profile first after this
#line
--display-fps-override= 60

# --- // Play_with_mpv:
#ontop=yes
#border=no
#window-scale=0.4
#geometry=100%:100%

#--profile-add= svp
# --- // SVP_PROFILE:
#[svp]
--input-ipc-server=/tmp/mpvsocket
--hr-seek-framedrop=no
--opengl-early-flush=yes
--vf= format=fmt=yuv420p
hwdec=auto-copy
hwdec-codecs=all
--no-resume-playback
--ignore-path-in-watch-later-config=yes


# --------------------------------------------------------------------- // PLAYER_SETTINGS //
#--loop-playlist=yes
#setpts=PTS*2
--vd-lavc-dr=yes
--vd-lavc-assume-old-x264= yes
#--user-agent=libmpv
--x11-bypass-compositor=no
#--player-operation-mode= pseudo-gui
--sub-visibility=no
--video-output-levels= full
#--rar-list-all-volumes= yes
#--directory-mode= recursive
#--corner-rounding= 1

# ---------------------------------------------------------------------- // AUDIO_SETTINGS //
#--video-sync=desync
--video-sync= display-resample
#--audio-device=
#--alsa/sysdefault:CARD= PCH
#audio-pitch-correction=no
#audio-channels=5.1
#audio-channels=auto
#volume-max=250
--no-audio

# ---------------------------------------------------------------------- // WINDOW_MARGINS //
#--window-scale= 0.500
#geometry=50%:50%
#--snap-window= yes
--stop-screensaver= always
#--osd-blur= 2
#--osd-border-size= 1
#--osd-duration= 8000
#--osd-on-seek= msg-bar
#--force-window= immediate
#--force-seekable= yes
#--display-tags= Title, Channerl_URL, service_name
#--fs= no
#--autofit-smaller= yes
#--geometry=50%+10+10/2
#--geometry=100%:100%
#--keep-open=always
#--keep-open-pause=no
#--taskbar-progress=yes
#--term-title= yes
#--title= ${?media-title:${media-title}}- mpv
#--no-border
#--osd-level=1
#--osd-bar=no
#save-position-on-quit=yes
#--video-rotate=<0-359|no>
#keepaspect=no
#--ontop= yes
#--on-all-workspaces= yes


# ------------------------------------------------------------------------ // PROFILES //
#[vdpau]
#--hqscaling=9
--scale=ewa_lanczossharp
#--scale=bilinear
#--cscale=bilinear
--cscale=spline36
--zimg-dither= error-diffusion
--zimg-scaler= spline36
--zimg-scaler-chroma= spline36
--no-correct-pts
--deband= yes
--deinterlace= yes
--interpolation= yes
--interpolation-preserve= yes
--linear-upscaling= yes
--interpolation-threshold= 0.03
#--tscale-param1= mitchell
#--tscale-param2= 0.5
#--sws-scaler= lanczos
--sws-fast=no
--sws-allow-zimg=yes
--zimg-fast=no
--tone-mapping-max-boost=2.0
#sharpen=5
#--gpu-dumb-mode=yes
#--gpu-context=wayland
vo=gpu

#[pyradio]
#volume=50

#[Act as a web browser]
# Pretend to be a web browser. Might fix playback with some streaming sites,
# but also will break with shoutcast streams.
#user-agent="Mozilla/5.0"
#cache=yes
#demuxer-max-bytes=123400KiB
#cache-pause=no
#demuxer-readahead-secs=20

#[anime4k]
#--glsl-shaders= /usr/share/anime4k


# ------------------------------------------------------------------- // MISC //
# --- // Screenshots:
--screenshot-format=png
--screenshot-png-compression=0

--screenshot-directory="~/Pictures/Screens"
--screenshot-template="%F - [%P]v%#01n"
#--screenshot-webp-lossless=yes
#--screenshot-webp-quality=100



# --- // Extension_behavior:
image-display-duration=inf

[extension.gif]
loop-file=inf

[extension.webm]
loop-file=inf

[extension.jpg]
--pause=yes

[extension.png]
--pause=yes
