#!/bin/sh
while read -r file; do
    case "$1" in
    "w")
        # Extract the original video file name from the thumbnail name
        video_path="${file##*/}"
        video_path="${video_path%.jpg}"
        full_video_path="$(find . -iname "$video_path.*" -type f \( -name "*.mp4" -o -name "*.mkv" -o -name "*.avi" -o -name "*.mov" -o -name "*.webm" -o -name "*.flv" -o -name "*.wmv" \) -print -quit)"

        # Play the video with mpv if the video file exists
        if [ -n "$full_video_path" ]; then
            mpv "$full_video_path" &
        else
            notify-send "Video not found" "Could not find the original video file for $file"
        fi
        ;;
    "c")
        [ -z "$destdir" ] && destdir="$(sed "s/#.*$//;/^\s*$/d" ${XDG_CONFIG_HOME:-$HOME/.config}/shell/bm-dirs | awk '{print $2}' | dmenu -l 20 -i -p "Copy file(s) to where?" | sed "s|~|$HOME|g")"
        [ ! -d "$destdir" ] && notify-send "$destdir is not a directory, cancelled." && exit
        cp "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file copied to $destdir." &
        ;;
    "m")
        [ -z "$destdir" ] && destdir="$(sed "s/#.*$//;/^\s*$/d" ${XDG_CONFIG_HOME:-$HOME/.config}/shell/bm-dirs | awk '{print $2}' | dmenu -l 20 -i -p "Move file(s) to where?" | sed "s|~|$HOME|g")"
        [ ! -d "$destdir" ] && notify-send "$destdir is not a directory, cancelled." && exit
        mv "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file moved to $destdir." &
        ;;
    "r")
        magick -rotate 90 "$file" "$file" ;;
    "R")
        magick -rotate -90 "$file" "$file" ;;
    "f")
        magick -flop "$file" "$file" ;;
    "y")
        printf "%s" "$file" | wl-copy -n &&
        notify-send "Copied to clipboard" "$file" &
        ;;
    "Y")
        readlink -f "$file" | wl-copy -n &&
        notify-send "Copied to clipboard" "$(readlink -f "$file")" &
        ;;
    "d")
        [ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted." ;;
    "g")
        if command -v gimp >/dev/null 2>&1; then setsid -f gimp "$file"; fi ;;
    "i")
        notify-send "File information" "$(mediainfo "$file" | sed "s/[ ]\+:/:/g;s/: /: <b>/;s/$/<\/b>/" | grep "<b>")" ;;
    esac
done
