# Conf 1
enable-rpc=true
rpc-listen-all=true
rpc-listen-port=6800
max-overall-download-limit=0
max-connection-per-server=10
max-concurrent-downloads=5
file-allocation=falloc
max-tries=5
retry-wait=30
continue=true
check-certificate=false
dir=/home/andro/Downloads
#bt-tracker=http://aaa.aa:80/announce,udp://bbb.bb:80/announce
bt-tracker=$(cat /home/$USER/.config/aria2/trackerlist.txt)

#Conf 2
listen-port=60000
dht-listen-port=60000
seed-ratio=1.0
max-upload-limit=50K
ftp-pasv=true
