#!/usr/bin/env bash

# Enhanced Alacritty Launch Script with Fallback Configuration and Error Handling
# Author: 4ndr0666
# Date: 10-01-24

# Path to Alacritty configuration file
CONFIG="$HOME/.config/wayfire/alacritty/alacritty.toml"
#DEFAULT_CONFIG="/etc/alacritty/alacritty.yml"

# Check if the custom configuration file exists
#if [ ! -f "$CONFIG" ]; then
#    echo "Custom config not found. Using default configuration."
#    CONFIG="$DEFAULT_CONFIG"
#fi

# Handle the input arguments and launch Alacritty accordingly
if [ "$1" == "-f" ]; then
	alacritty --class 'alacritty-float,alacritty-float' --config-file "$CONFIG"
elif [ "$1" == "-F" ]; then
	alacritty --class 'alacritty-fullscreen,alacritty-fullscreen' --config-file "$CONFIG" \
			  -o window.startup_mode="'Fullscreen'" \
			  window.padding.x=30 window.padding.y=30 \
			  window.opacity=0.95 font.size=14
else
	alacritty --config-file "$CONFIG"
fi
