#!/usr/bin/env bash

# Enhanced Mako Notifications Script with Improved Process Check

CONFIG="$HOME/.config/wayfire/mako/config"

if [[ ! `pidof mako` ]]; then
	mako --config ${CONFIG}
fi

# Check if Mako is running using pgrep
#if ! pgrep -x "mako" > /dev/null; then
#    mako --config "${CONFIG}"
#fi
