#!/usr/bin/env bash
# 4ndr0666

# === // KITTY.SH // === #
# Description: Launcher for the kitty terminal
DIR="$HOME/.config/hypr"
CONFIG="$DIR/kitty/kitty.conf"

if [[ "$1" == '-f' ]]; then
	kitty --class 'kitty-float' --config "$CONFIG"
elif [[ "$1" == '-F' ]]; then
	kitty --class 'kitty-fullscreen' --config "$CONFIG" \
		  --start-as fullscreen \
		  --override 'window_padding_width=30' \
		  --override 'font_size=14' \
		  --override 'background_opacity=0.95'
else
	kitty --config "$CONFIG" ${@}
fi
