#!/usr/bin/env bash
# 4ndr066

# === // STATUSBAR.SH // === #
# Desc: Custom launcher for waybar on hyprland.
CONFIG="$HOME/.config/waybar/config"
STYLE="$HOME/.config/waybar/style.css"

if [[ ! `pidof waybar` ]]; then
	waybar --bar main-bar --log-level error --config ${CONFIG} --style ${STYLE}
fi
