# Shell variables
# Generated by 'wal'
wallpaper='/home/andro/Wallpapers/background62.jpg'

# Special
background='#010101'
foreground='#dddddd'
cursor='#dddddd'

# Colors
color0='#010101'
color1='#474747'
color2='#575757'
color3='#676767'
color4='#777777'
color5='#8E8E8E'
color6='#AEAEAE'
color7='#dddddd'
color8='#9a9a9a'
color9='#474747'
color10='#575757'
color11='#676767'
color12='#777777'
color13='#8E8E8E'
color14='#AEAEAE'
color15='#dddddd'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
