#!/bin/bash

KEYBINDINGS=$(cat << EOL
Super + space                     root-menu
Alt + space                       client-menu
Alt + S + space                   client-list-combined-menu
C + Alt + space                   app-menu
Super + Tab                       NextWindow
Alt + Tab                         NextWindow
C + Alt + →                       GoToDesktop
C + Alt + ←                       GoToDesktop
Super + =                         addDesktop
Super + -                         RemoveDesktop
Super + d                         ToggleShowDesktop
C + S + R                         Obmenu Reload
C + S + BackSpace                 Restart
C + Alt + Delete                  Exit
Super + S + →                     SendToDesktop
Super + S + ←                     SendToDesktop
S + Super + 1                     SendToDesktop
Super + Alt + ↑                   MoveRelative
Super + Alt + ↓                   MoveRelative
Super + Alt + ←                   MoveRelative
Super + Alt + →                   MoveRelative
Super + C + →                     ResizeRelative
Super + C + ←                     ResizeRelative
Super + C + ↓                     ResizeRelative
Super + C + ↑                     ResizeRelative
Super + Alt + m                   Begin Interactive Moving
Super + Alt + r                   Begin Interactive
Super + ←                         UnmaximizeFull
Super + →                         UnmaximizeFull
Super + ↑                         MaximizeFull
Super + ↓                         UnmaximizeFull
Super + S + ↑                     UnmaximizeFull
Super + S + ↓                     UnmaximizeFull
Super + k                         Unmaximize
Super + S + k                     Unmaximize
Super + h                         Unmaximize
Super + S + h                     Unmaximize
Super + j                         Unmaximize
Super + S + j                     Unmaximize
Super + l                         Unmaximize
Super + S + l                     Unmaximize
Super + KP_1                      UnmaximizeFull
Super + KP_2                      UnmaximizeFull
Super + KP_3                      UnmaximizeFull
Super + KP_4                      UnmaximizeFull
Super + KP_5                      MAltximizeFull
Super + KP_6                      UnmaximizeFull
Super + KP_7                      UnmaximizeFull
Super + KP_8                      UnmaximizeFull
Super + KP_9                      UnmaximizeFull
Super + c                         Close
Super + q                         Close
Alt + F4                          Close
Alt + F5                          Iconify
Alt + F6                          ToggleMaximize
Alt + F7                          ToggleShade
Alt + F8                          ToggleDecorations
Alt + F9                          ToggleOmnipresent
Alt + F10                         ToggleFullscreen
Alt + F11                         ToggleawaysOnTop
Alt + F12                         ToggleAlwaysOnBottom
Print                             ob-screenshot --now
Alt + Print                       ob-screenshot --in5
S + Print                         ob-screenshot --in10
C + Print                         ob-screenshot --win
Super + Print                     ob-screenshot --area
Super + Return                    Alacritty
Super + f                         thunar
Super + Super                     firefox
Super + e                         geany
Alt + F1                          launcher
Super + n                         networkmanager_dmenu
Super + m                         music
Super + x                         powermenu
Super + s                         screenshot
Super + r                         runner
C + Alt + t                       xfce4-terminal
C + Alt + v                       alacritty -e vim
C + Alt + r                       alacritty -e ranger
C + Alt + h                       alacritty -e htop
C + Alt + l                       betterlockscreen --lock
Super + t                         ob-furminal
Super + p                         ob-colorpicker
C + Alt + m                       ob-music
Super + Escpe                     xkill
EOL
)

yad --title="Keybindings" \
    --text="$KEYBINDINGS" \
    --geometry="500x100" \
    --on-top \
    --scroll \
    --no-buttons \
    --skip-taskbar \
    --transparent \
    --mouse \
    --wrap \
    --fontname="Monaco Nerd Font 10"
