#!/usr/bin/env bash
# Author: 4ndr0666

# ============= // PLAYDIR //

# Description: No file is made, instead process substitution
#              send the playlist directly to mpv. Only media
#              files are selected through filtering and I/O 
#              overhead is avoided by not creating a temp file.

playdir() {
    if [ -z "$1" ]; then
        echo "No file or directory provided." >&2
        exit 1
    fi
    if [ -d "$1" ]; then
        target="$1"
    else
        target=$(dirname "$1")
    fi
    cd "$target" || exit 1
    #### Filtering for media files only:
    mpv --playlist=<(find "$(pwd)" -maxdepth 1 -type f \( \
          -iname "*.mp4" -o -iname "*.m4v" -o -iname "*.mkv" -o \
          -iname "*.avi" -o -iname "*.gif" -o -iname "*.mov" -o \
          -iname "*.3gp" -o -iname "*.ts" \)) --shuffle --loop=no
}
playdir "$1"
