CLICOLOR_FORCE: 1
GIT_PROTOCOL: ssh
GH_EDITOR: vim
GIT_EDITOR: vim
VISUAL: sublime-text-4
EDITOR: sublime-text-4
GH_BROWSER: brave-bin
BROWSER: brave
GH_PAGER: bat
PAGER: less
GH_PROMPT: enabled
aliases:
    co: pr checkout
    gp: git add. && git commit -m "$1" && git push
    ge: extensions list
