[%General]
Current%20version=1200
Last%20Opened=/home/andro/MegaDLs
Last%20Write%20Format=107
Save%20directory=/home/andro

[Options]
Aspectratio%20checked=false
BgColor%20checked=false
Check%20updates=true
ImageDir%20checked=true
Interpolation%20filter=0
Measure=0
Overwrite%20mode=false
Preview%20checked=true
Rename%20checked=true
Resolution%20checked=false
Scale%20checked=true
WindowSize=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3\x1e\0\0\0V\0\0\a|\0\0\x3\xd1\0\0\x3 \0\0\0k\0\0\az\0\0\x3\xcb\0\0\0\0\0\0\0\0\a\x80\0\0\x3 \0\0\0k\0\0\az\0\0\x3\xcb)

[Quality]
Jpeg%20quality=100
Png%20quality=9
Remove%20metadata=true
Webp%20compression%20value=4
Webp%20dithering=false
Webp%20lossless%20compression=false
Webp%20quality%20level=50
