CLICOLOR_FORCE: 1
GIT_PROTOCOL: ssh
GH_EDITOR: vim
GIT_EDITOR: vim
VISUAL: geany
EDITOR: geany
GH_BROWSER: brave
BROWSER: brave
GH_PAGER: bat
PAGER: less
GH_PROMPT: enabled
aliases:
    ge: extensions list
version: "1"
editor=: micro
editor: /usr/bin/micro
prefer_editor_prompt: enabled
pager: bat
browser: brave
