CLICOLOR_FORCE: 1
GIT_PROTOCOL: ssh
GH_EDITOR: nvim
GIT_EDITOR: nvim
VISUAL: lite-xl
EDITOR: lite-xl
GH_BROWSER: brave-beta
BROWSER: brave-beta
GH_PAGER: bat
PAGER: less
GH_PROMPT: enabled
aliases:
    ge: extensions list
version: "1"
editor=: micro
editor: /usr/bin/micro
prefer_editor_prompt: enabled
pager: bat
browser: brave-beta
