" Generated by vim-plug
" Wed 16 Jul 2025 10:37:06 PM CDT
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['ale'].commit = '4b1bf3ee8f8516dc52d0a64aef7b6f2723bfea77'
silent! let g:plugs['cmp-nvim-lsp'].commit = 'a8912b88ce488f411177fc8aed358b04dc246d7b'
silent! let g:plugs['goyo.vim'].commit = 'fa0263d456dd43f5926484d1c4c7022dfcb21ba9'
silent! let g:plugs['nerdtree'].commit = '9b465acb2745beb988eff3c1e4aa75f349738230'
silent! let g:plugs['nightfox.nvim'].commit = 'ba47d4b4c5ec308718641ba7402c143836f35aa9'
silent! let g:plugs['nvim-cmp'].commit = 'b5311ab3ed9c846b585c0c15b7559be131ec4be9'
silent! let g:plugs['nvim-lspconfig'].commit = 'dbfd8da6206b4ab0e2fe9b72a538f82e2b410102'
silent! let g:plugs['tabular'].commit = '12437cd1b53488e24936ec4b091c9324cafee311'
silent! let g:plugs['vim-airline'].commit = '5ca7f0b7fef4f174d57fd741b477bbbac0b7886a'
silent! let g:plugs['vim-commentary'].commit = '64a654ef4a20db1727938338310209b6a63f60c9'
silent! let g:plugs['vim-css-color'].commit = '14fd934cdd9ca1ac0e53511094e612eb9bace373'
silent! let g:plugs['vim-markdown'].commit = '8f6cb3a6ca4e3b6bcda0730145a0b700f3481b51'
silent! let g:plugs['vim-surround'].commit = '3d188ed2113431cf8dac77be61b842acb64433d9'
silent! let g:plugs['vimagit'].commit = 'fc7eda97da4f8182c8abbe6ea7befbd789b8b935'
silent! let g:plugs['vimwiki'].commit = '72792615e739d0eb54a9c8f7e0a46a6e2407c9e8'

PlugUpdate!

