" Generated by vim-plug
" Mon May 26 21:43:01 2025
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['ale'].commit = '80ff84db84ba172bfcdee5e2748924bb2249134b'
silent! let g:plugs['cmp-nvim-lsp'].commit = 'a8912b88ce488f411177fc8aed358b04dc246d7b'
silent! let g:plugs['goyo.vim'].commit = 'fa0263d456dd43f5926484d1c4c7022dfcb21ba9'
silent! let g:plugs['lightline.vim'].commit = 'e358557e1a9f9fc860416c8eb2e34c0404078155'
silent! let g:plugs['nerdtree'].commit = '9b465acb2745beb988eff3c1e4aa75f349738230'
silent! let g:plugs['nightfox.nvim'].commit = 'ba47d4b4c5ec308718641ba7402c143836f35aa9'
silent! let g:plugs['nvim-cmp'].commit = 'b5311ab3ed9c846b585c0c15b7559be131ec4be9'
silent! let g:plugs['nvim-lspconfig'].commit = 'd45702594afc661a9dfa95e96acf18c56006d4d9'
silent! let g:plugs['tabular'].commit = '12437cd1b53488e24936ec4b091c9324cafee311'
silent! let g:plugs['vim-airline'].commit = '41c5f54507fd865c8c00fe1f4bb390a59b6894ef'
silent! let g:plugs['vim-commentary'].commit = '64a654ef4a20db1727938338310209b6a63f60c9'
silent! let g:plugs['vim-css-color'].commit = '14fd934cdd9ca1ac0e53511094e612eb9bace373'
silent! let g:plugs['vim-mucomplete'].commit = '1b7227b9541c861f7b05b84d523764a9b1de78d8'
silent! let g:plugs['vim-surround'].commit = '3d188ed2113431cf8dac77be61b842acb64433d9'
silent! let g:plugs['vimagit'].commit = 'fc7eda97da4f8182c8abbe6ea7befbd789b8b935'
silent! let g:plugs['vimwiki'].commit = '72792615e739d0eb54a9c8f7e0a46a6e2407c9e8'

PlugUpdate!
