# Shell variables
# Generated by 'wal'
wallpaper='/home/andro/Wallpapers/Honeycomb Garuda SGS.png'

# Special
background='#0c0c0c'
foreground='#90c2c7'
cursor='#90c2c7'

# Colors
color0='#0c0c0c'
color1='#2B5B6C'
color2='#454546'
color3='#49546D'
color4='#38827F'
color5='#2C6892'
color6='#4967A2'
color7='#90c2c7'
color8='#64878b'
color9='#2B5B6C'
color10='#454546'
color11='#49546D'
color12='#38827F'
color13='#2C6892'
color14='#4967A2'
color15='#90c2c7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
